version: '3'

services:
  db:
    container_name: db
    image: postgres:16.3
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
